### ISSUE TITLE
2.9.2 still crashes without Tin

### ISSUE THREAD

**Issue by brisingraerowing** [voidsong-dragonfly/Magneticraft#6]
[Crash Log](https://gist.github.com/BrisingrAerowing/c60eed16103a8f5764de888b8ebfdd46)

**Comment by Lgmrszd** [comment]
Can confirm same issue with bare minimum of mods:
Forgelin-1.8.4
ImmersiveEngineering-0.12-98
IndustrialWires-1.8-38
Magneticraft_1.12-2.9.2-dev
MCTImmersiveTechnology-1.12.2-1.9.98
modelloader-1.1.7

**Comment by Pikabyte** [comment]
I'm getting a crash even with tin in the pack. The problem for me is that there's no tin plate. Why couldn't this mod just add a tin if only to be disabled if there are other tins in the pack? It should be a really simple fix tbh.
